# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ce53becfc711fce6767d737a441ee8c180511d5c49ae0511ee87575bce13e16eb7c2a4521cdc465c3c7310fff69acd5aaccf4e20547c99a19a611669a79efcb

test:
  secret_key_base: 85e6de27177dd27a86b43c0d842470eca74036770366bf53942ae536facf7c19f2452ab58e030dddff6e2cf731d30ae6874af5324274fdac867f3b877c0dfccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
